name: Build documentation and checks coverage

on: #quando é que estas Actions irão correr!
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  docs-coverage:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Setup Java JDK on ${{ matrix.os }}
        uses: actions/setup-java@v4.7.0
        with:
          distribution: 'oracle'
          java-version: '23'
      - name: Build using Maven
        run: mvn package
      - name: Uploads tests artifact
        uses: actions/upload-artifact@v4.6.0
        with:
          name: test-artifact-${{ github.run_number }}
          path: target/site/jacoco/
      - name: Uploads documentation(javadocs) artifact
        uses: actions/upload-artifact@v4.6.0
        with:
          name: documentation-artifact-${{ github.run_number }}
          path: target/apidocs/